plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'net.ltgt.errorprone' version '4.1.0'
}

group = 'org.learn.spring.boot'
version = '0.0.1-SNAPSHOT'
description = 'jspecify-null-safety'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {

    errorprone 'com.google.errorprone:error_prone_core:2.37.0'
    errorprone 'com.uber.nullaway:nullaway:0.12.6'

	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone {
        disableAllChecks = true
        option("NullAway:OnlyNullMarked", "true")
        option("NullAway:JSpecifyMode", "true")
        option("NullAway:CustomContractAnnotations", "org.springframework.lang.Contract")
        error("NullAway")
    }
}
